.TH ADF_BITMAP 1 "Dec 2023"
.SH NAME
adf_bitmap \- show or enforce rebuilding block allocation bitmap.

.SH SYNOPSIS
.B adf_bitmap <\fIcommand\fR> [\fIadf_device\fR]
.SH DESCRIPTION
\fBadf_bitmap\fR is a low-level filesystem utility allowing to display
or to enforce rebuilding the block allocation bitmap of an Amiga volume.

Commands available:
.TP
.B show
display block allocation bitmap of a volume
.TP
.B rebuild
enforce rebuilding block allocation bitmap of a volume (even if it is
marked as 'valid')
.
.SH SEE ALSO
.BR adf_show_metadata (1), adf_floppy_create (1), adf_floppy_format (1), unadf (1), adflib (3)
.SH NOTES
Detailed info about Commodore Amiga filesystems: http://lclevy.free.fr/adflib/adf_info.html
.SH AUTHOR
\fBadf_bitmap\fR was written by \fBTomasz Wolak\fR <tomas.wolak@gmail.com>,
as a part of the ADFlib (https://github.com/lclevy/ADFlib).
.PP
