#!/bin/sh
#
# Preform installation with CMake
#
# Installation prefix (directory) can be given as a parameter
# (otherwise the installation is peformed to the default place).
#

util/cmake_static_install $@
util/cmake_shared_install $@
